Massive rework of internal message handling and updated Switch Display

diff --git a/bin/xrandr-tui b/bin/xrandr-tui
--- a/bin/xrandr-tui
+++ b/bin/xrandr-tui
@@ -28,60 +28,109 @@
 	LIST_DEFAULT_RESOLUTIONS_WIDE="720x400 720x576 1152x864 1280x768 1280x960 1368x768 1440x900 1400x1050 1600x900 1680x1050 1600x1200"
 	DEFAULT_DISPLAY=""
 	DEFAULT_RESOLUTION=""
-	SHOW_HZ=false
+	DEFAULT_LINEAR_SOURCE=""
+	DEFAULT_LINEAR_TARGET=""
+	DEFAULT_SHOW_HZ=false
 	SKIP_CHECK=${SKIP_CHECK:-false}
+	WAIT=2
 #
 #	Script info
 #
 	script_name="xrandr-tui"
-	script_version=0.4
+	script_version=0.4.1
 	script_author="Simon Arjuna Erat (sea)"
 	script_homepage="https://github.com/sri-arjuna/xrandr-tui"
 	script_authors=""	# Add your names here, seperated by a comma ','
 #
 #	Variables : Messages
 #
-	MSG_HEADER_LEFT="$script_name ($script_version)"
-	MSG_HEADER_RIGHT="Brought to you by (sea)" # & ${script_authors:-noone else}"
-	MSG_TITLE="Current setup"
+	# Heading & Intro
+	MSG_MENU_HEADER_LEFT="$script_name ($script_version)"
+	MSG_MENU_HEADER_RIGHT="Brought to you by (sea)" # & ${script_authors:-noone else}"
+	MSG_MENU_CONFIG_PREVIEW="Current setup"
+	MSG_MENU_CONFIG_UNUSED="With these connected but unused displays:"
 	MSG_MENU_TITLE="Welcome to the main menu"
-	MSG_MENU_INTRO="What is your new setup?"
-	MSG_CONFIG_UNUSED_DISPLAYS="With these unused (but connected) displays:"
-	MSG_ORDER_FIRST="What is your first display (bottom,left) slot:"
-	MSG_ORDER_OTHER="What is the next display?"
-	MSG_ORDER_SOURCE="What is the source display?"
-	MSG_ORDER_TARGET="Add a target?"
-	MSG_SWITCH_INVALID_COUNT='Invalid count of connected displays: !2 = $(list.screens.connected)'
-	MSG_SCREEN_SRC="Use this output slot as source:"
-	MSG_DETECTED_SCREEN_SRC="Detected old active display slot:"
-	MSG_DETECTED_SCREEN_TRGT="Selected new output slot:"
-	MSG_DETECTED_SCREEN_MODE="Use mode/resolution autoselect?"
-	MSG_SWITCH_RES="Please select the resolution for:"
-	MSG_SELECT_RES_DISPLAY="Please select the display to change the resolution:"
-	MSG_SELECT_RES="Please select the new resolution for:"
-	MSG_MIRROR_NOTARGET="You have not selected a target for the mirror."
-	MSG_SCREEN_MIRROR_SRC="Detected old active display slot:"
-	MSG_SOURCE_CORRECT="Is this selection correct?"
-	MSG_SOURCE_CORRECT_NOT="The first item you select as target, will be taken as source."
-	MSG_LINEAR_SET_PRIMARY="Set primary screen (left):"
-	MSG_LINEAR_SET_LEFT="The previous display is left, next right one:"
-	MSG_LINEAR_SET_NEWLINE="The previous display is last right, next new line starts with output slot:"
-	MSG_SET_PRIMARY="Set as primary screen (bottom,left) slot:"
-	MSG_SCREEN_UPDATE="Next screen update in:"
-	MSG_DEFAULT_MAIN="Which is your default display when resetting?"
-	#MSG_DEFAULT_MAIN_=""
-	MSG_DEFAULT_RES="What resolution shall be set when resetting?"
-	#MSG_DEFAULT_RES_=""
-	MSG_DEFAULT_HZ="Use the refresh rate (hz) of the created modes for the name as well?"
-	MSG_MODE_ADD_TITLE="Add a new mode to slot:"
-	MSG_MODE_ADD_KIND="What kind of mode would you like to add?"
-	MSG_MODE_ADD_DISPLAY="Which display shall be used?"
-	MSG_MODE_ADD_EXISTS="The mode you wanted to add does already exist"
-	MSG_MODE_ADD_NEW="Please enter your desired resolution like: 1280x720"
-	MSG_MODE_ADD_ASK="Are you sure to use this:"
+	MSG_MENU_CONFIG_INTRO="What is your new setup?"
+	MSG_MENU_UPDATE="Next screen update in:"
+	
+	# Configuration screen
+	MSG_LABEL_CONFIG_TITLE="${script_name^} configuration"
+	MSG_LABEL_CONFIG_DEFAULT_DISPLAY="Which is your default display when resetting?"
+	MSG_LABEL_CONFIG_DEFAULT_RESOLUTION="What resolution shall be set when resetting?"
+	MSG_LABEL_CONFIG_DEFAULT_HZ="Which is the default refresh rate for your default display?"
+	MSG_LABEL_CONFIG_DEFAULT_SHOW_HZ="Use the HZ for the created modes as well?"
+	MSG_LABEL_CONFIG_DEFAULT_LINEAR_BASE="What will be the output most left?"
+	MSG_LABEL_CONFIG_DEFAULT_LINEAR_ORDER="What is the order of the monitors, from left to right:"
+	MSG_LABEL_CONFIG_DEFAULT_MIRROR_SOURCE="What is the source display?"
+	
+	# Task : mirror
+	MSG_TASK_MIRROR_NOTARGET="You have not selected a target for the mirror."
+	MSG_TASK_MIRROR_TARGET="Add a target?"
+	
+	# Task : linear
+	MSG_TASK_LINEAR_SET_PRIMARY="Set primary screen (left):"
+	MSG_TASK_LINEAR_SET_ORDER="The following screens are:"
+	MSG_TASK_LINEAR_NEXT="The previous display is left, next right one:"
+	# Task : multi-line
+	MSG_TASK_MULTILINE_NEWLINE="The previous display is last right, next new line starts with output slot:"
+	MSG_TASK_MULTILINE_SET_BREAKPOINTS="Of not equaliy spread (2 lines x 3 outputs), provide the monitors at which $screen_name shall make a new line:"
+	
+	# Task : resolution
+	#MSG_TASK_RESOLUTION_SELECT_DISPLAY="Please select the display to change the resolution:"
+	#MSG_TASK_RESOLUTION_SELECT_RES="Please select the new resolution for:"
+	MSG_TASK_RESOLUTION_DONE="Changed resolution:"
+	
+	# Task : switch
+	MSG_TASK_SWITCH_INVALID_COUNT='Invalid count of connected displays: !2 = $(list.screens.connected)'
+	
+	#MSG_TASK_SWITCH_DISP_CUR="The current display is:"
+	#MSG_TASK_SWITCH_DISP_NEW="The new display will be:"
+	#MSG_TASK_SWITCH_DISP_CHG="Do you want to use this?"
+	#MSG_TASK_SWITCH_RES="Please select the resolution for:"
+	
+	# Modes : add
+	MSG_TASK_MODE_ADD_TITLE="Add a new mode to slot:"
+	MSG_TASK_MODE_ADD_KIND="What kind of mode would you like to add?"
+	MSG_TASK_MODE_ADD_DISPLAY="Which display shall be used?"
+	MSG_TASK_MODE_ADD_EXISTS="The mode you wanted to add does already exist"
+	MSG_TASK_MODE_ADD_NEW="Please enter your desired resolution like: 1280x720"
+	MSG_TASK_MODE_ADD_ASK="Are you sure to use this:"
+	
+	# Modes : remove
 	MSG_MODE_RM_TITLE="Remove an old mode from slot:"
 	MSG_MODE_RM_ASK="Are you sure to remove this?"
-		
+	
+	
+	
+	
+	
+	# Shared
+	MSG_SHARED_DISPLAY_CURRENT="The currently used display is:"
+	MSG_SHARED_DISPLAY_FOUND="The found output display is:"
+	MSG_SHARED_DISPLAY_NEW="The new output display will be:"
+	MSG_SHARED_DISPLAY_CHANGE_INPUT="Please select the base display:"
+	MSG_SHARED_DISPLAY_CHANGE_OUTPUT="Please select a new output display:"
+	MSG_SHARED_DISPLAY_SELECTED="The selected display is:"
+	MSG_SHARED_CORRECT="Is this correct?"
+	
+	MSG_SHARED_RESOLUTION_CURRENT="The currently used resolution is:"
+	MSG_SHARED_RESOLUTION_CHANGE="Please select a new resolution for:"
+	
+	MSG_SHARED_SELECT_OUTPUT="Selected new output slot:"
+	
+	
+	MSG_DETECTED_SCREEN_SRC="Detected old active display slot:"
+	
+#	
+#	MSG_DETECTED_SCREEN_MODE="Use mode/resolution autoselect?"
+#	MSG_SET_PRIMARY="Set as primary screen (bottom,left) slot:"
+#	MSG_SCREEN_MIRROR_SRC="Detected old active display slot:"
+#	MSG_SCREEN_SRC="Use this output slot as source:"
+#	MSG_SOURCE_CORRECT="Is this selection correct?"
+#	MSG_SOURCE_CORRECT_NOT="The first item you select as target, will be taken as source."
+	
+	
+	
 #
 #	Variables
 #
@@ -89,7 +138,7 @@
 	declare XR=\xrandr AWK=\gawk GREP=\grep SED=\sed LS=\ls WHICH=\which
 	# Vars
 	declare CONF="$XCD/$script_name.conf" RAW_DATA="" ORDER="" LISTLENGTH=15
-	# other stuff
+	# Booleans
 	first=true		# Menu tweak
 	first_order=true	# MSG toggle tweak when setting order
 #
@@ -111,34 +160,41 @@
 	list.menu() { tmp=$($GREP "task.*()" "$($WHICH $0)"|$GREP -ve "list.menu" -ve "task.quit" -ve "#" -ve ^"#"|$AWK '{print $1}');echo "${tmp//task.}"|$SED s,\(\)*,,g; }
 	# Task functions
 	task.quit() { exit 0 ; }
-	task.switch() { 
+	task.switch() {
 	# Expects two connected displays
-	# Switches the the active to off, and actives the off one
+	# Switches the active to off, and uses the unused one
+		cur="$(screen.name)"
+		new="$(list.screens.connected|$SED s,$cur,,g)"
+			
 		tui-title "${FUNCNAME/task\.}"
-		cur=$(screen.name)
+		tui-print -E "$MSG_SHARED_DISPLAY_CURRENT" 	"$cur"
+		tui-print -E "$MSG_SHARED_DISPLAY_NEW" 		"$new"
 		
-		MSG_SWITCH_DISP_CUR="The current display is:"
-		MSG_SWITCH_DISP_CHG="Do you want to use this?"
+		RET=0
+		! tui-yesno "$MSG_SHARED_CORRECT" && \
+			tui-print -E "$MSG_SHARED_DISPLAY_CHANGE_INPUT ($cur)" && \
+			cur=$(tui-select $(list.screens.connected)) && \
+			tui-print -E "$MSG_SHARED_DISPLAY_CHANGE_OUTPUT ($new)" && \
+			RET=1 && \
+			new=$(tui-select $(list.screens.connected))
+		tui-status $RET "$MSG_SHARED_DISPLAY_SELECTED $new" || exit 1
 		
-		tui-print -E "$MSG_SWITCH_DISP_CUR $cur"
-		! tui-yesno "$MSG_SWITCH_DISP_CHG" && \
-		
-		tui-print -S $? "$MSG_DETECTED_SCREEN_SRC $cur"
-		
-		job.switch "$cur"
+		job.switch "$cur" "$new"
 	}
 	task.resolution() { 
 	# Change the resolution for the current active display
 	# Select which display if more than one is active
 		tui-title "${FUNCNAME/task\.}"
 		[ $(screen.name|grep [a-zA-Z]|wc -w) -gt 1  ] && \
-			tui-print -E "$MSG_SELECT_RES_DISPLAY" && \
+			tui-print -E "$MSG_SHARED_RESOLUTION_CHANGE" && \
 			this=$(tui-select $(screen.name)) || \
 			this=$(screen.name)
-		tui-print -E "$MSG_SELECT_RES" "$this"
+		tui-print -E "$MSG_SHARED_RESOLUTION_CHANGE" "$this"
 		res=$(tui-select $(list.modes $this))
 		
-		(set -x;$XR --output $this --mode $res)
+		#(set -x;
+		$XR --output $this --mode $res #)
+		tui-status $? "$MSG_TASK_RESOLUTION_DONE $this @ $res"
 		exit $?
 	}
 	task.mirror() { # SRC TRGT1 TRGT2 ..
@@ -210,7 +266,7 @@
 		list.modes $(screen.name) | $GREP -q "${mode_lbl/_*}" && \
 			tui-print -S 1 "$MSG_MODE_ADD_EXISTS" && \
 			exit 1
-		$SHOW_HZ || mode_lbl="${mode_lbl/_*}"
+		$DEFAULT_SHOW_HZ || mode_lbl="${mode_lbl/_*}"
 		$XR --newmode $mode_lbl $mode_numbers
 		$XR --addmode $display $mode_lbl
 		$XR --output $display --mode $mode_lbl
@@ -220,42 +276,76 @@
 	#
 		display="$(screen.name)"
 		
-		tui-title "$MSG_MODE_RM_TITLE $display"
+		tui-print -T "${FUNCNAME/task\.} $display"
 		res_rm=$(tui-select $(list.modes $display))
 		
 		if tui-yesno "${MSG_MODE_RM_ASK} $res_rm ($display)"
 		then	$(set -x;$XR --delmode $display $res_rm)
 			$(set -x;$XR --rmmode "$res_rm")
-			
 		fi
 		return $?
 	}
 	#task.multiline() { tui-title "TODO ${FUNCNAME/task\.}" ; tui-list -1 $@ ; }
-	task.reset() { job.reset.all ; $XR --output $DEFAULT_DISPLAY --mode $DEFAULT_RESOLUTION --primary ; }
-	job.reset.all() { for d in $(list.screens.connected);do $XR --output $d --off;done;}
-	task.config() { tui-conf-editor -H "$script_name ($script_version)" --write-no-exist --option DEFAULT_DISPLAY --values "$($0 --list-connected)" --default "$(screen.name)" --option DEFAULT_RESOLUTION --values "$(list.modes $(tui-conf-get $CONF DEFAULT_DISPLAY))" --default "$(screen.size)" --option DEFAULT_HZ --values "30 60 75 100" --default 60 --option SHOW_HZ --values "true false" --default "false" "$CONF" ;}
+	task.reset() { job.reset.all ; $XR --output ${DEFAULT_DISPLAY:-$(screen.name)} --mode ${DEFAULT_RESOLUTION:-$(screen.size)} --primary ; }
+	task.config() { 
+	# Show the configuration editor
+	# Upon every call it rewrites the default values if none exists
+		tui-conf-editor	\
+			-H "$script_name ($script_version)" \
+			-T "$MSG_LABEL_CONFIG_TITLE" \
+			--option DEFAULT_DISPLAY \
+				--label "$MSG_LABEL_CONFIG_DEFAULT_DISPLAY" \
+				--values "$($0 --list-connected)" \
+				--default "$(screen.name)" \
+			--option DEFAULT_RESOLUTION \
+				--label "$MSG_LABEL_CONFIG_DEFAULT_RESOLUTION" \
+				--values "$(list.modes $(screen.name))" \
+				--default "$(screen.size)" \
+			--option DEFAULT_LINEAR_ORDER \
+				--label "$MSG_LABEL_CONFIG_DEFAULT_LINEAR_ORDER" \
+				--values "$(list.screens.connected)" \
+				--default "$(list.screens.connected|$SED s,$(screen.name),,g)" \
+			--option DEFAULT_MIRROR_SOURCE \
+				--label "$MSG_LABEL_CONFIG_DEFAULT_MIRROR_SOURCE" \
+				--values "$(list.screens.connected)" \
+				--default "$(screen.name)" \
+			--option DEFAULT_HZ \
+				--label "$MSG_LABEL_CONFIG_DEFAULT_HZ" \
+				--values "30 60 75 100" \
+				--default 60 \
+			--option DEFAULT_SHOW_HZ \
+				--label "$MSG_LABEL_CONFIG_DEFAULT_SHOW_HZ" \
+				--values "true false" \
+				--default "false" \
+			--write-no-exist "$CONF"
+	}
+#
+#	Jobs
+#
 	job.firsttime() { tui-bol-dir "$XCD";touch "$CONF";task.config;}
-	job.switch() { # CUR_SCRN
+	job.mirror.source() { list.screens.connected|$SED s,${DEFAULT_DISPLAY:-$(screen.name)},,g|$AWK '{print $1}' ; }
+	job.reset.all() { for d in $(list.screens.connected);do $XR --output $d --off;done;}
+	job.switch() { # CUR NEW [auto] 
 	# Expects two connected displays
 	# Switches the the active to off, and activateses the off one
-		tui-print -T "${FUNCNAME/task\.}"
-		cur="$1" ; [ -n "$cur" ] 
-		tui-status $? "$MSG_DETECTED_SCREEN_SRC" "$cur" || exit 1
-		
-		new=$(list.screens);RET=$?
-		new="${new/$cur}"
-		tui-print -S $RET "$MSG_DETECTED_SCREEN_TRGT" "$new"
-		
-		tui-yesno "$MSG_DETECTED_SCREEN_MODE" && \
-			MODE=$(list.modes $new | head -n1) || \
-			{ tui-print -T "$MSG_SWITCH_RES" "$new" ;MODE=$(tui-select $(list.modes $new));}
-		
-		(set -x;$XR --output $cur --off)
-		(set -x;$XR --output $new --mode $MODE)
+		# Even if called by arguments, cant switch an unequal amount of connected displays
+		[ 2 -ne $(list.screens.connected|wc -w) ] && tui-print -S 1 "$MSG_TASK_SWITCH_INVALID_COUNT" && exit 1
+		if [ -z "$3" ]
+		then	# Ask for the screen resolution
+			tui-print -E
+			tui-print -E "$MSG_SHARED_RESOLUTION_CHANGE" "$2"
+			MODE=$(tui-select $(list.modes $2 ))
+		else	# Get automatic
+			MODE=$($XR | $GREP -A$LISTLENGTH $2 | $AWK '/+/ {print $1}'|head -n1)
+		fi	
+		(set -x;$XR --output $1 --off)
+		(set -x;$XR --output $2 --mode $MODE)
 		exit $RET
 	}
-	# Show repeated stuff
-	show.config.current() { C=0;while [ -n "${AR_SCRN[$C]}" ] ;do tui-print -E "${AR_SCRN[$C]}" "${AR_RES[$C]}";((C++));done;tui-print -E "$MSG_CONFIG_UNUSED_DISPLAYS" "$(list.screens.unused)";}
+#
+# 	Show repeated or special stuff
+#
+	show.config.current() { C=0;while [ -n "${AR_SCRN[$C]}" ] ;do tui-print -E "$MSG_SHARED_DISPLAY_CURRENT"  "${AR_SCRN[$C]} @ ${AR_RES[$C]}";((C++));done;tui-print -E "$MSG_MENU_CONFIG_UNUSED" "$(list.screens.unused)";}
 	show.version() { printf '%s\n' "$script_name, Version $script_version" "Copyright (C) 2015 by $script_author" "License GNU General Public License (GPL) or later <http://www.gnu.org/licenses/gpl.html>" "" "This is free software; you are free to change and redistribute it." "There is NO WARRANTY, to the extent permitted by law.";exit 0;}
 	show.help() {
 	# Show help screen
@@ -273,7 +363,8 @@
 		OPTIONS
 		 		-h|--help		Show this screen and exit
 		 		--version		Show the version and exit
-		 		-C|--config		Edit the configuration
+		 		-C|--config		Change the configuration
+		 		-E|--edit		Edit the configuration manually
 		 		
 		 		--list-connected	List connected slots and exit
 		 		--list-unused		List free slots and exit
@@ -293,7 +384,7 @@
 		exit 0
 	}
 #
-#	Action & preparations
+#	Preparations
 #
 	data.get
 	declare -a AR_SCRN=($(screen.name)) 
@@ -301,11 +392,11 @@
 	$SKIP_CHECK ||  { [ -f "$CONF" ] || job.firsttime ; }
 	source "$CONF"
 #
-#	Action : Get options
+#	Get options
 #
 	GETOPT=$(getopt \
-		--options	"hCL" \
-		--longoptions	"help,version,config,mirror,list-unused,list-used,list-connected,reset,switch" \
+		--options	"hCE" \
+		--longoptions	"help,version,edit,config,mirror,list-unused,list-used,list-connected,reset,switch" \
 		--name 		"${0##*/}" -- "${@}" \
 	)
 	eval set -- "${GETOPT}";
@@ -317,32 +408,39 @@
 		-C|--config)	task.config
 				exit $?
 				;;
+		-E|--edit)	tui-edit "$CONF"
+				exit $?
+				;;
 		# -----------------------------------------------
+		# The SKIP_CHECK is required to bypass check on first usage
 		--list-connected)
 				SKIP_CHECK=true list.screens.connected
 				exit 0
 				;;
-		--list-unused)
-				SKIP_CHECK=true list.screens.unused
+		# The SKIP_CHECK is required to bypass check on first usage
+		--list-unused)	SKIP_CHECK=true list.screens.unused
 				exit 0
 				;;
-		--list-used)
-				screen.name
+		--list-used)	screen.name
 				exit 0
 				;;
+		# Use defaults from config, for WM integration
 		--reset)	task.reset
 				exit $?
 				;;
-		--switch)	# Switch silently, to be used for WMs hotkey-binding as example
-				job.switch "$(screen.name)"<<-EO_SCRIPT
-				y
-				EO_SCRIPT
+		# Switch silently, to be used for WMs hotkey-binding as example
+		--switch)	
+				cur="$(screen.name)"
+				new="$(list.screens.connected|$SED s,$cur,,g)"
+				job.switch $cur $new auto
 				exit $?
 				;;
-		--mirror)	# Switch silently, to be used for WMs hotkey-binding as example
-				task.mirror "$DEFAULT_DISPLAY $(list.screens.connected|$SED s,$DEFAULT_DISPLAY,,g)"<<-EO_SCRIPT
-				y
-				EO_SCRIPT
+		# Use defaults from config, for WM integration
+		--mirror)	task.mirror ${DEFAULT_MIRROR_SOURCE}
+				exit $?
+				;;
+		# Use defaults from config, for WM integration
+		--linear)	task.linear $DEFAULT_DISPLAY $DEFAULT_LINEAR_ORDER
 				exit $?
 				;;
 		esac
@@ -350,19 +448,20 @@
 #
 #	Display
 #
-	while :;do ! $first && tui-wait 3 "$MSG_SCREEN_UPDATE" || first=false ; clear
-		tui-print -H "$MSG_HEADER_LEFT" "$MSG_HEADER_RIGHT"
-		tui-print -T "$MSG_TITLE"
+	while :;do ! $first && tui-wait $WAIT "$MSG_MENU_UPDATE" || first=false ; clear
+		tui-print -H "$MSG_MENU_HEADER_LEFT" "$MSG_MENU_HEADER_RIGHT"
+		tui-print -T "$MSG_MENU_CONFIG_PREVIEW"
 		show.config.current
 		
 		tui-print -T "$MSG_MENU_TITLE"
-		tui-print -E "$MSG_MENU_INTRO"
+		tui-print -E "$MSG_MENU_CONFIG_INTRO"
 		
 		# Get action
 		action=$(tui-select quit $(list.menu))
 		# Quit or define order of displays
 		if [ "$action" = "quit" ]
-		then	task.$action
+		then	break
+			task.$action
 		elif [ -z "$ORDER" ]
 		then	case "$action" in
 			linear|multiline)
@@ -371,29 +470,29 @@
 				do
 					ORDER+=" $item"
 					$first_order && \
-						tui-print -E "$MSG_ORDER_FIRST" && \
+						tui-print -E "$MSG_TASK_LINEAR_SET_PRIMARY" && \
 						first=false || \
-						tui-print -E "$MSG_ORDER_OTHER"
+						tui-print -E "$MSG_TASK_LINEAR_SET_ORDER"
 					item=$(tui-select done $(list.screens))
 				done
 				;;
 			mirror)
-				tui-print -E "$MSG_ORDER_SOURCE"
+				tui-print -E "$MSG_SHARED_DISPLAY_CHANGE_INPUT"
 				SOURCE=$(tui-select $(list.screens.connected))
 				
 				this=""
-				while 	tui-print -E "$MSG_ORDER_TARGET"
-					tui-print -E "Src: $SOURCE // Targets: $TARGET"
+				while 	tui-print -E "$MSG_SHARED_DISPLAY_CHANGE_OUTPUT"
+					tui-print -E "Src: $SOURCE" "Targets: $TARGET"
 					this=$(tui-select done $(list.screens.connected|$SED s,"$SOURCE",,g))
 					[ ! done = $this ]
 				do
 					TARGET+=" $this";this=""
 				done
-				[ -z "$TARGET" ] && tui-print -S 1 "$MSG_MIRROR_NOTARGET" && exit 1
+				[ -z "$TARGET" ] && tui-print -S 1 "$MSG_TASK_MIRROR_NOTARGET" && exit 1
 				ORDER="$SOURCE $TARGET"
 				;;
-			switch)	[ 2 -ne $(list.screens|wc -w) ] && \
-					tui-print -S 1 "$MSG_SWITCH_INVALID_COUNT" && \
+			switch)	[ 2 -ne $(list.screens.connected|wc -w) ] && \
+					tui-print -S 1 "$MSG_TASK_SWITCH_INVALID_COUNT" && \
 					exit 1
 				;;
 			esac
